# My dictionary 

## numpy

In [39]:
import numpy as np

#ARRAY 
arrays  =  np.array([1,2,3])       # create an array with numpy
zeros   =  np.zeros((5,5))         # array of zero
ones    =  np.ones((5,5))          # array of one
full    =  np.full((5,5),zeros)    # full with any number
eye     =  np.eye(5)               # indetify matrix
random  =  np.random.random((5,5)) # random numbers

#MATH
add     =  np.add(eye,ones)         # add or x+y 
sub     =  np.subtract(eye,ones)    # asubtract or x-y  
mult    =  np.multiply(eye,ones)    # multiply or x*y  
div     =  np.divide(eye,ones)      # divide or x/y  
sqrt    =  np.sqrt(eye,ones)        # sqrt  
dot     =  np.dot(eye,ones)         # to multiply a vector by a matrix, and to multiply matrices
dot2    =  eye.dot(ones)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
eye 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])