# numpy

In [75]:
import numpy as np

### Array

##### type = numpy.ndarray

In [76]:
c = np.array([1,2,3,4,5,6,12,13,3,11])

type(c)

numpy.ndarray

<br>

##### shape = size of np.array

In [25]:
c = np.array([[1,2,3],[3,2,1,3]]) # size = 2 elements = 3 in [0] and 4 in [1]
print(c.shape)

b = np.array([[1,2,3],[4,5,6]])    
print(b.shape)                     # size = 2 elements = 3 in [0] and 3 in [1] 

(2,)
(2, 3)


<br>

#### functions to create arrays

In [41]:
#create arrays of zero
#first = line,second = row
z = np.zeros((3,4)) #two array and four zeros
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [43]:
#create arrays of one
o = np.ones([7,8]) # 7 array and 8 one
o

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
#create arrays of any values
number = np.full((3,10),5) 
number

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [13]:
#create a identify matrix
eye = np.eye(10)
eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
random = np.random.random((4,6))
random

array([[0.51359458, 0.99463666, 0.86293994, 0.07464193, 0.2171906 ,
        0.8231078 ],
       [0.75188093, 0.43924382, 0.69580909, 0.59109406, 0.72074985,
        0.64837184],
       [0.05361044, 0.06384128, 0.2710169 , 0.62848183, 0.56064469,
        0.29182112],
       [0.24187595, 0.94874902, 0.79553525, 0.64684622, 0.80908733,
        0.62474737]])

In [40]:
idl = (random > 0.5)  
idl

array([[False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [False,  True,  True, False,  True,  True],
       [ True, False, False, False, False, False]])

In [71]:
random[:3] += 10

<br>

<br>

### slice

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = a[:2,1:3] #first check entire array in slice ,second elements in array


In [77]:
# using slice as index
b = np.array([0, 1, 0, 1])
a[np.arange(4),b]

array([11,  5, 17, 21])

### Array math

In [410]:
x = np.array([np.random.randint(10),np.random.randint(10)],dtype=np.float64)
y = np.array([10,20],dtype=np.float64)

print('the value of x is ' + str(x) + ' and y is '+ str(y))
print("the sum is  " + str(x+y))
print("the sub is  " + str(np.subtract(x,y)))
print("the mult is " + str(x*y))
print("the div is  " + str(np.divide(x,y)))
print("the sqrt is " + str(np.around(np.sqrt(x,y))))

the value of x is [8. 4.] and y is [10. 20.]
the sum is  [18. 24.]
the sub is  [ -2. -16.]
the mult is [80. 80.]
the div is  [0.8 0.2]
the sqrt is [3. 2.]
