# numpy

In [3]:
import numpy as np

##### type = numpy.ndarray

In [21]:
c = np.array([1,2,3,4,5,6,12,13,3,11])

type(c)

numpy.ndarray

<br>

##### shape = size of np.array

In [25]:
c = np.array([[1,2,3],[3,2,1,3]]) # size = 2 elements = 3 in [0] and 4 in [1]
print(c.shape)

b = np.array([[1,2,3],[4,5,6]])    
print(b.shape)                     # size = 2 elements = 3 in [0] and 3 in [1] 

(2,)
(2, 3)


<br>

#### functions to create arrays

In [41]:
#create arrays of zero
z = np.zeros((3,4)) #two array and four zeros
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [43]:
#create arrays of one
o = np.ones([7,8]) # 7 array and 8 one
o

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [51]:
#create arrays of any values
number = np.full((3,4),z) 
number

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<br>